-- Create product table
CREATE TABLE `bms`.`product` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(100) NOT NULL,
  `PRICE` DECIMAL(10,2) NOT NULL,
  `CREATED_ON` DATETIME NOT NULL,
  `UPDATED_ON` DATETIME NOT NULL,
  `ACTIVE_STATUS` VARCHAR(50) NOT NULL,
  `CATEGORY_ID` INT NULL,
  PRIMARY KEY (`ID`));

-- Create category table
CREATE TABLE `bms`.`category` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(100) NOT NULL,
  `CREATED_ON` DATETIME NOT NULL,
  `UPDATED_ON` DATETIME NOT NULL,
  `ACTIVE_STATUS` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`ID`));

